// <auto-generated />
using System;
using ApiNet8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240720170342_UsuarioNullAtributo")]
    partial class UsuarioNullAtributo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiNet8.Models.Club.ClubHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParametrosClubId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParametrosClubId");

                    b.ToTable("ClubHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Club.ParametrosClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorBannerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("IconoPlataforma")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LogoGrande")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LogoPequenio")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerfilClubId")
                        .HasColumnType("int");

                    b.Property<string>("QuienesSomos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoBannerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoFooterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilClubId");

                    b.ToTable("ParametrosClub");
                });

            modelBuilder.Entity("ApiNet8.Models.Club.PerfilClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePerfilClub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PerfilClub");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.EstadoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadoEvento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "Evento creado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7714),
                            NombreEstado = "Creado",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Evento cancelado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7716),
                            NombreEstado = "Cancelado",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Evento finalizado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7718),
                            NombreEstado = "Finalizado",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 4,
                            DescripcionEstado = "Evento iniciado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7719),
                            NombreEstado = "Iniciado",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 5,
                            DescripcionEstado = "Evento suspendido",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7720),
                            NombreEstado = "Suspendido",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 6,
                            DescripcionEstado = "Evento en entretiempo",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7721),
                            NombreEstado = "Entretiempo",
                            UsuarioEditor = 1
                        });
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Banner")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CupoMaximo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("EventoLleno")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<string>("LinkStream")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InstalacionId");

                    b.HasIndex("TipoEventoId");

                    b.ToTable("Evento");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Evento");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.HistorialEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEventoId")
                        .HasColumnType("int");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoEventoId");

                    b.HasIndex("EventoId");

                    b.ToTable("HistorialEvento");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreTipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoEvento");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.AsistenciaLeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AsistioAlumno")
                        .HasColumnType("bit");

                    b.Property<bool>("ClaseCompleta")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.ToTable("AsistenciaLeccion");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantJugadores")
                        .HasColumnType("int");

                    b.Property<int>("CantJugadoresEnBanca")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodosMax")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasAdvertencia")
                        .HasColumnType("int");

                    b.Property<int>("TarjetasExpulsion")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Disciplina");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.InscripcionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeccionId")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeccionId");

                    b.ToTable("InscripcionUsuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Leccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantMaxima")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<string>("Horarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Leccion");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.LeccionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LeccionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.LeccionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeccionEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("LeccionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeccionEstadoId");

                    b.HasIndex("LeccionId");

                    b.ToTable("LeccionHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.NoticiasYNotificaciones.Noticias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.Property<string>("tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ApiNet8.Models.NoticiasYNotificaciones.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Adjunto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notificacion");
                });

            modelBuilder.Entity("ApiNet8.Models.NoticiasYNotificaciones.UsuarioNotificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioNotificacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.AccionPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Minuto")
                        .HasColumnType("int");

                    b.Property<int>("NroJugador")
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAccionPartidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.HasIndex("TipoAccionPartidoId");

                    b.ToTable("AccionPartido");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Local")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EquipoEstado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "Equipo activo",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7746),
                            NombreEstado = "Activo",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Equipo inactivo",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7749),
                            NombreEstado = "Inactivo",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Equipo suspendido",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7751),
                            NombreEstado = "Suspendido",
                            UsuarioEditor = 1
                        });
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EquipoEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoEstadoId");

                    b.HasIndex("EquipoId");

                    b.ToTable("EquipoHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("JugadoresEnBanca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JugadoresEnCancha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("EquipoPartido");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EquipoUsuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Estadistica", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarcaEstadistica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuntajeTipoAccion")
                        .HasColumnType("int");

                    b.Property<string>("RazonBaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estadistica");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TipoAccionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoAccionEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoAccionPartidoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoAccionEstadoId");

                    b.HasIndex("TipoAccionPartidoId");

                    b.ToTable("TipoAccionHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<bool>("ModificaTarjetasAdvertencia")
                        .HasColumnType("bit");

                    b.Property<bool>("ModificaTarjetasExpulsion")
                        .HasColumnType("bit");

                    b.Property<string>("NombreTipoAccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("secuencial")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("TipoAccionPartido");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.Instalacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instalacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.InstalacionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InstalacionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.InstalacionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstalacionEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionEstadoId");

                    b.HasIndex("InstalacionId");

                    b.ToTable("InstalacionHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstalacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstalacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ApiNet8.Models.TYC.HistorialTerminosYCondiciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TerminosYCondicionesId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerminosYCondicionesId");

                    b.ToTable("HistorialTerminosYCondiciones");
                });

            modelBuilder.Entity("ApiNet8.Models.TYC.TerminosYCondiciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TYC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TerminosYCondiciones");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.PartidoFase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FasePartido")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PartidoFaseId")
                        .HasColumnType("int");

                    b.Property<int>("TorneoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartidoFaseId");

                    b.HasIndex("TorneoId");

                    b.ToTable("PartidoFase");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Banner")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CantEquipos")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DisciplinaId");

                    b.ToTable("Torneo");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.TorneoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TorneoEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.TorneoHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TorneoEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneoEstadoId");

                    b.HasIndex("TorneoId");

                    b.ToTable("TorneoHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.CodigoVerificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigoVerificacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.EstadoSolicitudAsociacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EstadoSolicitudAsociacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.GrupoFamiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentosGrupoFamiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DuenioGrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreGrupoFamiliar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("duenioGrupoFamiliar")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DuenioGrupoFamiliarId");

                    b.ToTable("GrupoFamiliar");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerfilUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilUsuarioId");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.PerfilPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PermisoId");

                    b.ToTable("PerfilPermiso");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.PerfilUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PerfilUsuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funcionalidades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permiso");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.SolicitudAsociacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudAsociacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.SolicitudAsociacionHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoSolicitudAsociacionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SolicitudAsociacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoSolicitudAsociacionId");

                    b.HasIndex("SolicitudAsociacionId");

                    b.ToTable("SolicitudAsociacionHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CodPostal")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeporteFavorito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAceptacionTYC")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCambioContrasena")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.UsuarioEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEditor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsuarioEstado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescripcionEstado = "Usuario activo en el club",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7448),
                            NombreEstado = "Activo",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 2,
                            DescripcionEstado = "Usuario bloqueado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7462),
                            NombreEstado = "Bloqueado",
                            UsuarioEditor = 1
                        },
                        new
                        {
                            Id = 3,
                            DescripcionEstado = "Usuario desactivado",
                            FechaCreacion = new DateTime(2024, 7, 20, 14, 3, 40, 696, DateTimeKind.Local).AddTicks(7464),
                            NombreEstado = "Desactivado",
                            UsuarioEditor = 1
                        });
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.UsuarioHistorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambioEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsuarioEditor")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioEstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioHistorial");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Partido", b =>
                {
                    b.HasBaseType("ApiNet8.Models.Eventos.Evento");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GanadorId")
                        .HasColumnType("int");

                    b.Property<int?>("LocalId")
                        .HasColumnType("int");

                    b.Property<int?>("PartidoFaseId")
                        .HasColumnType("int");

                    b.Property<int?>("Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Set")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VisitanteId")
                        .HasColumnType("int");

                    b.HasIndex("GanadorId");

                    b.HasIndex("LocalId");

                    b.HasIndex("PartidoFaseId");

                    b.HasIndex("VisitanteId");

                    b.HasDiscriminator().HasValue("Partido");
                });

            modelBuilder.Entity("ApiNet8.Models.Club.ClubHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Club.ParametrosClub", null)
                        .WithMany("clubHistoriales")
                        .HasForeignKey("ParametrosClubId");
                });

            modelBuilder.Entity("ApiNet8.Models.Club.ParametrosClub", b =>
                {
                    b.HasOne("ApiNet8.Models.Club.PerfilClub", "PerfilClub")
                        .WithMany()
                        .HasForeignKey("PerfilClubId");

                    b.Navigation("PerfilClub");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Asistencia", b =>
                {
                    b.HasOne("ApiNet8.Models.Eventos.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Evento", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Reservas.Instalacion", "Instalacion")
                        .WithMany()
                        .HasForeignKey("InstalacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Eventos.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Instalacion");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.HistorialEvento", b =>
                {
                    b.HasOne("ApiNet8.Models.Eventos.EstadoEvento", "EstadoEvento")
                        .WithMany()
                        .HasForeignKey("EstadoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Eventos.Evento", null)
                        .WithMany("HistorialEventoList")
                        .HasForeignKey("EventoId");

                    b.Navigation("EstadoEvento");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Inscripcion", b =>
                {
                    b.HasOne("ApiNet8.Models.Eventos.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.AsistenciaLeccion", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Leccion", "Leccion")
                        .WithMany()
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Disciplina", b =>
                {
                    b.HasOne("ApiNet8.Models.Eventos.Evento", null)
                        .WithMany("Disciplinas")
                        .HasForeignKey("EventoId");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.InscripcionUsuario", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Lecciones.Leccion", "Leccion")
                        .WithMany()
                        .HasForeignKey("LeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Leccion", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Lecciones.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Disciplina");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.LeccionHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.LeccionEstado", "LeccionEstado")
                        .WithMany()
                        .HasForeignKey("LeccionEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Lecciones.Leccion", null)
                        .WithMany("LeccionHistoriales")
                        .HasForeignKey("LeccionId");

                    b.Navigation("LeccionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.NoticiasYNotificaciones.UsuarioNotificacion", b =>
                {
                    b.HasOne("ApiNet8.Models.NoticiasYNotificaciones.Notificacion", "Notificacion")
                        .WithMany()
                        .HasForeignKey("NotificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notificacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.AccionPartido", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.TipoAccionPartido", "TipoAccionPartido")
                        .WithMany()
                        .HasForeignKey("TipoAccionPartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("TipoAccionPartido");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Equipo", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Lecciones.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.EquipoEstado", "EquipoEstado")
                        .WithMany()
                        .HasForeignKey("EquipoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.Equipo", null)
                        .WithMany("EquipoHistoriales")
                        .HasForeignKey("EquipoId");

                    b.Navigation("EquipoEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoPartido", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.EquipoUsuario", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.Equipo", null)
                        .WithMany("EquipoUsuarios")
                        .HasForeignKey("EquipoId");

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Estadistica", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.AsistenciaLeccion", "AsistenciaLeccion")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.Equipo", "Equipo")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.TipoAccionPartido", "TipoAccionPartido")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsistenciaLeccion");

                    b.Navigation("Equipo");

                    b.Navigation("Partido");

                    b.Navigation("TipoAccionPartido");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.TipoAccionEstado", "TipoAccionEstado")
                        .WithMany()
                        .HasForeignKey("TipoAccionEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Partidos.TipoAccionPartido", null)
                        .WithMany("TipoAccionHistoriales")
                        .HasForeignKey("TipoAccionPartidoId");

                    b.Navigation("TipoAccionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionPartido", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.InstalacionHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Reservas.InstalacionEstado", "InstalacionEstado")
                        .WithMany()
                        .HasForeignKey("InstalacionEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Reservas.Instalacion", null)
                        .WithMany("InstalacionHistoriales")
                        .HasForeignKey("InstalacionId");

                    b.Navigation("InstalacionEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.Reserva", b =>
                {
                    b.HasOne("ApiNet8.Models.Reservas.Instalacion", "Instalacion")
                        .WithMany()
                        .HasForeignKey("InstalacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instalacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.TYC.HistorialTerminosYCondiciones", b =>
                {
                    b.HasOne("ApiNet8.Models.TYC.TerminosYCondiciones", null)
                        .WithMany("HistorialTerminosYCondicionesList")
                        .HasForeignKey("TerminosYCondicionesId");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.PartidoFase", b =>
                {
                    b.HasOne("ApiNet8.Models.Torneos.PartidoFase", null)
                        .WithMany("Llave")
                        .HasForeignKey("PartidoFaseId");

                    b.HasOne("ApiNet8.Models.Torneos.Torneo", "Torneo")
                        .WithMany()
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneo");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.Torneo", b =>
                {
                    b.HasOne("ApiNet8.Models.Lecciones.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Lecciones.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.TorneoHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Torneos.TorneoEstado", "TorneoEstado")
                        .WithMany()
                        .HasForeignKey("TorneoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Torneos.Torneo", null)
                        .WithMany("TorneoHistoriales")
                        .HasForeignKey("TorneoId");

                    b.Navigation("TorneoEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.CodigoVerificacion", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.GrupoFamiliar", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "DuenioGrupoFamiliar")
                        .WithMany()
                        .HasForeignKey("DuenioGrupoFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuenioGrupoFamiliar");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Perfil", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.PerfilUsuario", null)
                        .WithMany("Perfiles")
                        .HasForeignKey("PerfilUsuarioId");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.PerfilPermiso", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.PerfilUsuario", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", null)
                        .WithMany("PerfilesUsuario")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.SolicitudAsociacion", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.SolicitudAsociacionHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.EstadoSolicitudAsociacion", "EstadoSolicitudAsociacion")
                        .WithMany()
                        .HasForeignKey("EstadoSolicitudAsociacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.SolicitudAsociacion", null)
                        .WithMany("SolicitudAsociacionHistoriales")
                        .HasForeignKey("SolicitudAsociacionId");

                    b.Navigation("EstadoSolicitudAsociacion");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Usuario", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.GrupoFamiliar", null)
                        .WithMany("Integrantes")
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("ApiNet8.Models.Partidos.Partido", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("PartidoId");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.UsuarioHistorial", b =>
                {
                    b.HasOne("ApiNet8.Models.Usuarios.UsuarioEstado", "UsuarioEstado")
                        .WithMany()
                        .HasForeignKey("UsuarioEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiNet8.Models.Usuarios.Usuario", null)
                        .WithMany("UsuarioHistoriales")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("UsuarioEstado");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Partido", b =>
                {
                    b.HasOne("ApiNet8.Models.Partidos.EquipoPartido", "Ganador")
                        .WithMany()
                        .HasForeignKey("GanadorId");

                    b.HasOne("ApiNet8.Models.Partidos.EquipoPartido", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId");

                    b.HasOne("ApiNet8.Models.Torneos.PartidoFase", null)
                        .WithMany("Partidos")
                        .HasForeignKey("PartidoFaseId");

                    b.HasOne("ApiNet8.Models.Partidos.EquipoPartido", "Visitante")
                        .WithMany()
                        .HasForeignKey("VisitanteId");

                    b.Navigation("Ganador");

                    b.Navigation("Local");

                    b.Navigation("Visitante");
                });

            modelBuilder.Entity("ApiNet8.Models.Club.ParametrosClub", b =>
                {
                    b.Navigation("clubHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Eventos.Evento", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("HistorialEventoList");
                });

            modelBuilder.Entity("ApiNet8.Models.Lecciones.Leccion", b =>
                {
                    b.Navigation("LeccionHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Equipo", b =>
                {
                    b.Navigation("EquipoHistoriales");

                    b.Navigation("EquipoUsuarios");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.TipoAccionPartido", b =>
                {
                    b.Navigation("TipoAccionHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Reservas.Instalacion", b =>
                {
                    b.Navigation("InstalacionHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.TYC.TerminosYCondiciones", b =>
                {
                    b.Navigation("HistorialTerminosYCondicionesList");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.PartidoFase", b =>
                {
                    b.Navigation("Llave");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("ApiNet8.Models.Torneos.Torneo", b =>
                {
                    b.Navigation("TorneoHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.GrupoFamiliar", b =>
                {
                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.PerfilUsuario", b =>
                {
                    b.Navigation("Perfiles");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.SolicitudAsociacion", b =>
                {
                    b.Navigation("SolicitudAsociacionHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Usuarios.Usuario", b =>
                {
                    b.Navigation("PerfilesUsuario");

                    b.Navigation("UsuarioHistoriales");
                });

            modelBuilder.Entity("ApiNet8.Models.Partidos.Partido", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
